/* tslint:disable */
/* eslint-disable */
/**
 * Edison Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information about the logged-in user.
 * @export
 * @interface AuthorStatus
 */
export interface AuthorStatus {
    /**
     * 
     * @type {string}
     * @memberof AuthorStatus
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorStatus
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorStatus
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorStatus
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorStatus
     */
    username?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthorStatus
     */
    permissions: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof AuthorStatus
     */
    complimentaryUploadsRemaining: number;
    /**
     * 
     * @type {number}
     * @memberof AuthorStatus
     */
    purchasedUploadsRemaining: number;
    /**
     * 
     * @type {number}
     * @memberof AuthorStatus
     */
    subscriptionUploadsRemaining: number;
    /**
     * 
     * @type {boolean}
     * @memberof AuthorStatus
     */
    restrictedModels: boolean;
}

/**
 * Check if a given object implements the AuthorStatus interface.
 */
export function instanceOfAuthorStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "permissions" in value;
    isInstance = isInstance && "complimentaryUploadsRemaining" in value;
    isInstance = isInstance && "purchasedUploadsRemaining" in value;
    isInstance = isInstance && "subscriptionUploadsRemaining" in value;
    isInstance = isInstance && "restrictedModels" in value;

    return isInstance;
}

export function AuthorStatusFromJSON(json: any): AuthorStatus {
    return AuthorStatusFromJSONTyped(json, false);
}

export function AuthorStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'nickname': !exists(json, 'nickname') ? undefined : json['nickname'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'permissions': json['permissions'],
        'complimentaryUploadsRemaining': json['complimentaryUploadsRemaining'],
        'purchasedUploadsRemaining': json['purchasedUploadsRemaining'],
        'subscriptionUploadsRemaining': json['subscriptionUploadsRemaining'],
        'restrictedModels': json['restrictedModels'],
    };
}

export function AuthorStatusToJSON(value?: AuthorStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'email': value.email,
        'nickname': value.nickname,
        'username': value.username,
        'permissions': value.permissions,
        'complimentaryUploadsRemaining': value.complimentaryUploadsRemaining,
        'purchasedUploadsRemaining': value.purchasedUploadsRemaining,
        'subscriptionUploadsRemaining': value.subscriptionUploadsRemaining,
        'restrictedModels': value.restrictedModels,
    };
}

