/* tslint:disable */
/* eslint-disable */
/**
 * Edison Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * basic author information with only enough to display in a list and link to author specific pages
 * @export
 * @interface AuthorListItem
 */
export interface AuthorListItem {
    /**
     * 
     * @type {string}
     * @memberof AuthorListItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorListItem
     */
    name?: string;
}

/**
 * Check if a given object implements the AuthorListItem interface.
 */
export function instanceOfAuthorListItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function AuthorListItemFromJSON(json: any): AuthorListItem {
    return AuthorListItemFromJSONTyped(json, false);
}

export function AuthorListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function AuthorListItemToJSON(value?: AuthorListItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

