/* tslint:disable */
/* eslint-disable */
/**
 * Edison Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HistoryEventType } from './HistoryEventType';
import {
    HistoryEventTypeFromJSON,
    HistoryEventTypeFromJSONTyped,
    HistoryEventTypeToJSON,
} from './HistoryEventType';

/**
 * history event
 * @export
 * @interface DetailedHistoryEvent
 */
export interface DetailedHistoryEvent {
    /**
     * 
     * @type {Date}
     * @memberof DetailedHistoryEvent
     */
    eventTime: Date;
    /**
     * 
     * @type {HistoryEventType}
     * @memberof DetailedHistoryEvent
     */
    eventType: HistoryEventType;
    /**
     * 
     * @type {string}
     * @memberof DetailedHistoryEvent
     */
    eventSubType: string;
    /**
     * 
     * @type {string}
     * @memberof DetailedHistoryEvent
     */
    message: string;
    /**
     * Lots of unstructured data
     * @type {any}
     * @memberof DetailedHistoryEvent
     */
    details?: any | null;
}

/**
 * Check if a given object implements the DetailedHistoryEvent interface.
 */
export function instanceOfDetailedHistoryEvent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "eventTime" in value;
    isInstance = isInstance && "eventType" in value;
    isInstance = isInstance && "eventSubType" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function DetailedHistoryEventFromJSON(json: any): DetailedHistoryEvent {
    return DetailedHistoryEventFromJSONTyped(json, false);
}

export function DetailedHistoryEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedHistoryEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eventTime': (new Date(json['eventTime'])),
        'eventType': HistoryEventTypeFromJSON(json['eventType']),
        'eventSubType': json['eventSubType'],
        'message': json['message'],
        'details': !exists(json, 'details') ? undefined : json['details'],
    };
}

export function DetailedHistoryEventToJSON(value?: DetailedHistoryEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'eventTime': (value.eventTime.toISOString()),
        'eventType': HistoryEventTypeToJSON(value.eventType),
        'eventSubType': value.eventSubType,
        'message': value.message,
        'details': value.details,
    };
}

