/* tslint:disable */
/* eslint-disable */
/**
 * Edison Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const HistoryEventType = {
    Author: 'AUTHOR',
    Payment: 'PAYMENT',
    Subscription: 'SUBSCRIPTION',
    Manuscript: 'MANUSCRIPT'
} as const;
export type HistoryEventType = typeof HistoryEventType[keyof typeof HistoryEventType];


export function HistoryEventTypeFromJSON(json: any): HistoryEventType {
    return HistoryEventTypeFromJSONTyped(json, false);
}

export function HistoryEventTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryEventType {
    return json as HistoryEventType;
}

export function HistoryEventTypeToJSON(value?: HistoryEventType | null): any {
    return value as any;
}

