/* tslint:disable */
/* eslint-disable */
/**
 * Edison Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Overall status:
  * `PENDING` - Waiting to be processed
  * `PROCESSING` - Being processed
  * `DONE` - Done processing

 * @export
 */
export const ManuscriptStatus = {
    Pending: 'PENDING',
    Processing: 'PROCESSING',
    Done: 'DONE'
} as const;
export type ManuscriptStatus = typeof ManuscriptStatus[keyof typeof ManuscriptStatus];


export function ManuscriptStatusFromJSON(json: any): ManuscriptStatus {
    return ManuscriptStatusFromJSONTyped(json, false);
}

export function ManuscriptStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManuscriptStatus {
    return json as ManuscriptStatus;
}

export function ManuscriptStatusToJSON(value?: ManuscriptStatus | null): any {
    return value as any;
}

