/* tslint:disable */
/* eslint-disable */
/**
 * Edison Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ManuscriptProgress } from './ManuscriptProgress';
import {
    ManuscriptProgressFromJSON,
    ManuscriptProgressFromJSONTyped,
    ManuscriptProgressToJSON,
} from './ManuscriptProgress';

/**
 * Information about a manuscript
 * @export
 * @interface ManuscriptRevision
 */
export interface ManuscriptRevision {
    /**
     * 
     * @type {string}
     * @memberof ManuscriptRevision
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ManuscriptRevision
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ManuscriptRevision
     */
    audience: string;
    /**
     * 
     * @type {string}
     * @memberof ManuscriptRevision
     */
    genre: string;
    /**
     * 
     * @type {ManuscriptProgress}
     * @memberof ManuscriptRevision
     */
    progress: ManuscriptProgress;
    /**
     * 
     * @type {number}
     * @memberof ManuscriptRevision
     */
    modelVersion: number;
    /**
     * 
     * @type {Date}
     * @memberof ManuscriptRevision
     */
    created: Date;
}

/**
 * Check if a given object implements the ManuscriptRevision interface.
 */
export function instanceOfManuscriptRevision(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "audience" in value;
    isInstance = isInstance && "genre" in value;
    isInstance = isInstance && "progress" in value;
    isInstance = isInstance && "modelVersion" in value;
    isInstance = isInstance && "created" in value;

    return isInstance;
}

export function ManuscriptRevisionFromJSON(json: any): ManuscriptRevision {
    return ManuscriptRevisionFromJSONTyped(json, false);
}

export function ManuscriptRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManuscriptRevision {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'audience': json['audience'],
        'genre': json['genre'],
        'progress': ManuscriptProgressFromJSON(json['progress']),
        'modelVersion': json['modelVersion'],
        'created': (new Date(json['created'])),
    };
}

export function ManuscriptRevisionToJSON(value?: ManuscriptRevision | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'audience': value.audience,
        'genre': value.genre,
        'progress': ManuscriptProgressToJSON(value.progress),
        'modelVersion': value.modelVersion,
        'created': (value.created.toISOString()),
    };
}

