/* tslint:disable */
/* eslint-disable */
/**
 * Edison Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Status for a manuscript upload
 * @export
 * @interface ManuscriptUploadResponse
 */
export interface ManuscriptUploadResponse {
    /**
     * 
     * @type {string}
     * @memberof ManuscriptUploadResponse
     */
    manuscriptId: string;
    /**
     * 
     * @type {string}
     * @memberof ManuscriptUploadResponse
     */
    revisionId: string;
    /**
     * 
     * @type {string}
     * @memberof ManuscriptUploadResponse
     */
    statusMessage?: string;
}

/**
 * Check if a given object implements the ManuscriptUploadResponse interface.
 */
export function instanceOfManuscriptUploadResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "manuscriptId" in value;
    isInstance = isInstance && "revisionId" in value;

    return isInstance;
}

export function ManuscriptUploadResponseFromJSON(json: any): ManuscriptUploadResponse {
    return ManuscriptUploadResponseFromJSONTyped(json, false);
}

export function ManuscriptUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManuscriptUploadResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'manuscriptId': json['manuscriptId'],
        'revisionId': json['revisionId'],
        'statusMessage': !exists(json, 'statusMessage') ? undefined : json['statusMessage'],
    };
}

export function ManuscriptUploadResponseToJSON(value?: ManuscriptUploadResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'manuscriptId': value.manuscriptId,
        'revisionId': value.revisionId,
        'statusMessage': value.statusMessage,
    };
}

