/* tslint:disable */
/* eslint-disable */
/**
 * Edison Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatchText
 */
export interface MatchText {
    /**
     * 
     * @type {string}
     * @memberof MatchText
     */
    match: string;
    /**
     * 
     * @type {string}
     * @memberof MatchText
     */
    noMatch: string;
}

/**
 * Check if a given object implements the MatchText interface.
 */
export function instanceOfMatchText(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "match" in value;
    isInstance = isInstance && "noMatch" in value;

    return isInstance;
}

export function MatchTextFromJSON(json: any): MatchText {
    return MatchTextFromJSONTyped(json, false);
}

export function MatchTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchText {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'match': json['match'],
        'noMatch': json['noMatch'],
    };
}

export function MatchTextToJSON(value?: MatchText | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'match': value.match,
        'noMatch': value.noMatch,
    };
}

