/* tslint:disable */
/* eslint-disable */
/**
 * Edison Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ManuscriptRevision } from './ManuscriptRevision';
import {
    ManuscriptRevisionFromJSON,
    ManuscriptRevisionFromJSONTyped,
    ManuscriptRevisionToJSON,
} from './ManuscriptRevision';

/**
 * 
 * @export
 * @interface PageOfManuscriptRevision
 */
export interface PageOfManuscriptRevision {
    /**
     * 
     * @type {string}
     * @memberof PageOfManuscriptRevision
     */
    manuscriptTitle: string;
    /**
     * 
     * @type {number}
     * @memberof PageOfManuscriptRevision
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageOfManuscriptRevision
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof PageOfManuscriptRevision
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof PageOfManuscriptRevision
     */
    totalElements: number;
    /**
     * 
     * @type {Array<ManuscriptRevision>}
     * @memberof PageOfManuscriptRevision
     */
    content: Array<ManuscriptRevision>;
}

/**
 * Check if a given object implements the PageOfManuscriptRevision interface.
 */
export function instanceOfPageOfManuscriptRevision(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "manuscriptTitle" in value;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "totalPages" in value;
    isInstance = isInstance && "totalElements" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function PageOfManuscriptRevisionFromJSON(json: any): PageOfManuscriptRevision {
    return PageOfManuscriptRevisionFromJSONTyped(json, false);
}

export function PageOfManuscriptRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageOfManuscriptRevision {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'manuscriptTitle': json['manuscriptTitle'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalPages': json['totalPages'],
        'totalElements': json['totalElements'],
        'content': ((json['content'] as Array<any>).map(ManuscriptRevisionFromJSON)),
    };
}

export function PageOfManuscriptRevisionToJSON(value?: PageOfManuscriptRevision | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'manuscriptTitle': value.manuscriptTitle,
        'page': value.page,
        'pageSize': value.pageSize,
        'totalPages': value.totalPages,
        'totalElements': value.totalElements,
        'content': ((value.content as Array<any>).map(ManuscriptRevisionToJSON)),
    };
}

