/* tslint:disable */
/* eslint-disable */
/**
 * Edison Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DetailedHistoryEvent } from './DetailedHistoryEvent';
import {
    DetailedHistoryEventFromJSON,
    DetailedHistoryEventFromJSONTyped,
    DetailedHistoryEventToJSON,
} from './DetailedHistoryEvent';

/**
 * 
 * @export
 * @interface PageOfDetailedHistoryEvent
 */
export interface PageOfDetailedHistoryEvent {
    /**
     * 
     * @type {number}
     * @memberof PageOfDetailedHistoryEvent
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageOfDetailedHistoryEvent
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof PageOfDetailedHistoryEvent
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof PageOfDetailedHistoryEvent
     */
    totalElements: number;
    /**
     * 
     * @type {Array<DetailedHistoryEvent>}
     * @memberof PageOfDetailedHistoryEvent
     */
    content: Array<DetailedHistoryEvent>;
}

/**
 * Check if a given object implements the PageOfDetailedHistoryEvent interface.
 */
export function instanceOfPageOfDetailedHistoryEvent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "totalPages" in value;
    isInstance = isInstance && "totalElements" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function PageOfDetailedHistoryEventFromJSON(json: any): PageOfDetailedHistoryEvent {
    return PageOfDetailedHistoryEventFromJSONTyped(json, false);
}

export function PageOfDetailedHistoryEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageOfDetailedHistoryEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalPages': json['totalPages'],
        'totalElements': json['totalElements'],
        'content': ((json['content'] as Array<any>).map(DetailedHistoryEventFromJSON)),
    };
}

export function PageOfDetailedHistoryEventToJSON(value?: PageOfDetailedHistoryEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalPages': value.totalPages,
        'totalElements': value.totalElements,
        'content': ((value.content as Array<any>).map(DetailedHistoryEventToJSON)),
    };
}

