/* tslint:disable */
/* eslint-disable */
/**
 * Edison Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Author } from './Author';
import {
    AuthorFromJSON,
    AuthorFromJSONTyped,
    AuthorToJSON,
} from './Author';

/**
 * 
 * @export
 * @interface PageOfAuthor
 */
export interface PageOfAuthor {
    /**
     * 
     * @type {number}
     * @memberof PageOfAuthor
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageOfAuthor
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof PageOfAuthor
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof PageOfAuthor
     */
    totalElements: number;
    /**
     * 
     * @type {Array<Author>}
     * @memberof PageOfAuthor
     */
    content: Array<Author>;
}

/**
 * Check if a given object implements the PageOfAuthor interface.
 */
export function instanceOfPageOfAuthor(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "totalPages" in value;
    isInstance = isInstance && "totalElements" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function PageOfAuthorFromJSON(json: any): PageOfAuthor {
    return PageOfAuthorFromJSONTyped(json, false);
}

export function PageOfAuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageOfAuthor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalPages': json['totalPages'],
        'totalElements': json['totalElements'],
        'content': ((json['content'] as Array<any>).map(AuthorFromJSON)),
    };
}

export function PageOfAuthorToJSON(value?: PageOfAuthor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalPages': value.totalPages,
        'totalElements': value.totalElements,
        'content': ((value.content as Array<any>).map(AuthorToJSON)),
    };
}

