/* tslint:disable */
/* eslint-disable */
/**
 * Edison Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HistoryEvent } from './HistoryEvent';
import {
    HistoryEventFromJSON,
    HistoryEventFromJSONTyped,
    HistoryEventToJSON,
} from './HistoryEvent';

/**
 * 
 * @export
 * @interface PageOfHistoryEvent
 */
export interface PageOfHistoryEvent {
    /**
     * 
     * @type {number}
     * @memberof PageOfHistoryEvent
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageOfHistoryEvent
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof PageOfHistoryEvent
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof PageOfHistoryEvent
     */
    totalElements: number;
    /**
     * 
     * @type {Array<HistoryEvent>}
     * @memberof PageOfHistoryEvent
     */
    content: Array<HistoryEvent>;
}

/**
 * Check if a given object implements the PageOfHistoryEvent interface.
 */
export function instanceOfPageOfHistoryEvent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "totalPages" in value;
    isInstance = isInstance && "totalElements" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function PageOfHistoryEventFromJSON(json: any): PageOfHistoryEvent {
    return PageOfHistoryEventFromJSONTyped(json, false);
}

export function PageOfHistoryEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageOfHistoryEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalPages': json['totalPages'],
        'totalElements': json['totalElements'],
        'content': ((json['content'] as Array<any>).map(HistoryEventFromJSON)),
    };
}

export function PageOfHistoryEventToJSON(value?: PageOfHistoryEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalPages': value.totalPages,
        'totalElements': value.totalElements,
        'content': ((value.content as Array<any>).map(HistoryEventToJSON)),
    };
}

