/* tslint:disable */
/* eslint-disable */
/**
 * Edison Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Manuscript } from './Manuscript';
import {
    ManuscriptFromJSON,
    ManuscriptFromJSONTyped,
    ManuscriptToJSON,
} from './Manuscript';

/**
 * 
 * @export
 * @interface PageOfManuscript
 */
export interface PageOfManuscript {
    /**
     * 
     * @type {number}
     * @memberof PageOfManuscript
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PageOfManuscript
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof PageOfManuscript
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof PageOfManuscript
     */
    totalElements: number;
    /**
     * 
     * @type {Array<Manuscript>}
     * @memberof PageOfManuscript
     */
    content: Array<Manuscript>;
}

/**
 * Check if a given object implements the PageOfManuscript interface.
 */
export function instanceOfPageOfManuscript(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "totalPages" in value;
    isInstance = isInstance && "totalElements" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function PageOfManuscriptFromJSON(json: any): PageOfManuscript {
    return PageOfManuscriptFromJSONTyped(json, false);
}

export function PageOfManuscriptFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageOfManuscript {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalPages': json['totalPages'],
        'totalElements': json['totalElements'],
        'content': ((json['content'] as Array<any>).map(ManuscriptFromJSON)),
    };
}

export function PageOfManuscriptToJSON(value?: PageOfManuscript | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalPages': value.totalPages,
        'totalElements': value.totalElements,
        'content': ((value.content as Array<any>).map(ManuscriptToJSON)),
    };
}

